baseURL = 'https://blog.zhx589.top/'
locale = 'zh-cn'
title = "ZhX589's Blog"
paginate= 5
theme = "PaperMod"
timeZone = "Asia/Shanghai"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

metaDataFormat = "yaml"
hasCJKLanguage = true

[minify]
  disableXML = true
  minifyOutput = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  env = "production"
  title = "ZhX589 笔记"
  description = "ZhX589 的个人笔记，主要和计算机相关。"
  keywords = ["Blog", "计算机", "笔记"]
  author = "ZhX589"
  images = ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat = "2006年01月02日 15:04"
  defaultTheme = "auto"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.assets]
    favicon = "/ZhX589_256x256.ico"
    favicon16x16 = "/ZhX589_256x16.ico"
    favicon32x32 = "/ZhX589_32x32.ico"
    apple_touch_icon = "/ZhX589_256x256.ico"
    safari_pinned_tab = "/ZhX589_256x256.ico"

  [params.label]
    text = "Home"
    icon = "/ZhX589_256x256.ico"
    iconHeight = 35

  [params.profileMode]
    enabled = true
    title = "ZhX589"
    subtitle = "Segui il tuo corso, e lascia dir le genti. "
    imageUrl = "https://q1.qlogo.cn/g?b=qq&nk=2029837068&s=640"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "my image"

    [[params.profileMode.buttons]]
      name = "文章"
      url = "posts"

    [[params.profileMode.buttons]]
      name = "标签"
      url = "tags"

    [[params.profileMode.buttons]]
      name = "关于"
      url = "about"

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Enjoy your reading!"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/Xiaohei_ZhX589"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/ZhX589"

  [[params.socialIcons]]
    name = "bilibili"
    url = "https://space.bilibili.com/3493262669122054"

  [params.analytics]
    [params.analytics.google]
      SiteVerificationTag = "XYZabc"
    [params.analytics.bing]
      SiteVerificationTag = "XYZabc"
    [params.analytics.yandex]
      SiteVerificationTag = "XYZabc"

  [params.cover]
    hidden = true
    hiddenInList = true
    hiddenInSingle = true

  [params.editPost]
    URL = "https://github.com/<path_to_repo>/content"
    Text = "Suggest Changes"
    appendFilePath = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    limit = 10
    keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "categories"
  name = "分类"
  url = "/categories/"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 30

[[menu.main]]
  identifier = "travellings"
  name = "开往"
  url = "https://www.travellings.cn/go.html"
  weight = 40

pygmentsUseClasses = true

[markup]
  [markup.highlight]
    noClasses = false
    # anchorLineNos = true
    # codeFences = true
    # guessSyntax = true
    # lineNos = true
    # style = "monokai"
